# Generated by Django 4.2.5 on 2023-10-12 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0002_remove_mainbranch_branch_id_mainbranch_branch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='appoinment_id',
        ),
        migrations.RemoveField(
            model_name='mainbranch',
            name='branch_id',
        ),
        migrations.DeleteModel(
            name='Appoinment',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Mainbranch',
        ),
    ]
