# Generated by Django 4.2.5 on 2023-10-15 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0006_remove_branch_appoinment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinment',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appoint.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appoinment',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appoinment',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='branch',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mainbranch',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
