# Generated by Django 4.2.5 on 2023-10-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0007_appoinment_branch_appoinment_is_cancel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='limit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
