# Generated by Django 4.2.5 on 2023-10-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0008_branch_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_main_branch',
            field=models.BooleanField(default=False),
        ),
    ]
